baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Pieces"


[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name

[menu]

  [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        pre = "edit"
        url = "/post/"
        weight = 2

    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3

[taxonomies]
    tag ="tags"

[params]
    containerMaxWidth = "700px"
    dateFormat = "Jan 02, 2006"
    homeText ="You just made a hugo blog"

[Author]
        name ="Josphat Mutuku"
        # avatar="img/avatar.png

